### PR TITLE
Fix the company backend

### PR DESCRIPTION
**Pull request by cpitclaudel**
Fix the interface of the company-omnisharp backend. Is it still supported though? It's synchronous, so it's pretty slow for me.

### CODE REVIEW

**Comment by sp3ctum** [comment]
Thanks!

@nosami I remember you having a pretty fast company completion. Did you have some special configuration?

**Comment by nosami** [comment]
It's slow by default, but not because of it being synchronous - it has a built in delay before it tries to fetch completions.

try `'(company-idle-delay 0.03)` or some other small number.

It's fast even with flex searching turned on for me. I use these settings for that (from @bbbscarter)

```
(setq omnisharp-company-match-type 'company-match-flx)
(setq gc-cons-threshold 20000000)
```

**Comment by sp3ctum** [comment]
Ah yes. If this is it, we need to add it to the readme or some place.

2015-07-09 17:55 GMT+03:00 Jason Imison <notifications@github.com>:

**Comment by cpitclaudel** [comment]
Hmmm. I'm not sure the delay is the actual issue. I use company pretty heavily, so I have `company-idle-delay` set to zero. I have a similar setting regarding gc settings, to avoid a garbage collection during startup.

I just tested `company-omnisharp` again on a small file and it works wonderfully, so the problem is with large files. I'm not sure if anything can be done with the current architecture, though.

I'm surprised that async made it slower; maybe there was a bug somewhere? Company's async support is very basic, and mostly just consists in calling the right callback after a while; note that it doesn't spawn a thread for you or anything like that, so you need to rely on one of Emacs' native async operations (like url-retrieve, or subprocesses).

On the company topic, setting `company-tooltip-align-annotations` to `t` would probably obviate the need for the colon (`:`) that currently separates members from their types (they'll just be cleanly lined up to the right).

**Comment by sp3ctum** [comment]
Perhaps the temporary file thing you did slowed it down with larger files.
Could this be the case? In any case the performance may change with the
stdio interface. I'll try to get a working version released some time today
so we can try it out.

I originally started with auto-complete-mode and only recently switched to
company-mode. I haven't really tried out company-mode yet.

2015-07-10 8:31 GMT+03:00 Clément Pit--Claudel <notifications@github.com>:

**Comment by cpitclaudel** [comment]
I can't say: I never managed to get results for large files without writing the arguments to disk first :)

Company has a very clean interface, and @dgutov is a wonderful maintainer; when I started working on company-coq I evaluated both, and eventually gave up on auto-complete.

**Pull request merged**
