### PR TITLE
Update to rc4 dotnet and latest released omnisharp-roslyn

### PR DESCRIPTION
**Pull request by alistair**

### CODE REVIEW

**Comment by sp3ctum** [comment]
@razzmatazz you did some changes to the integration tests script. Were they exactly like this?
Do you think that could work with regards to the tests?

**Comment by razzmatazz** [comment]
@sp3ctum , @alistair .travis.yaml needs an update

@alistair – could you update .travis.yaml in this PR too to fix the build?

**Comment by razzmatazz** [comment]
I also think we need to relax version check in run-integration-tests.sh to something like "1.0*", like in my change here:
 - https://github.com/OmniSharp/omnisharp-emacs/pull/282/files#diff-0a3dba1d214aefb2c9160a2e5246f4a5L3

**Comment by alistair** [comment]
Been trying to get this working,   will try again today but is there a nice way of replicating the travis build locally.   as it "works on my machine" and the push fail cycle is getting old :)

**Comment by alistair** [comment]
@sp3ctum @razzmatazz I seem to have it mostly working,   only 1 test is seemingly timing out.

Sadly this doesnt happen locally and im not 100% sure whether its just omnisharp taking some time to warm up or not.

**Comment by alistair** [comment]
btw you will see that I increased the timeout to 4 (aka double) and that didnt help :(

**Comment by sp3ctum** [comment]
It tests integration with company and auto-complete iirc.. also there seems to be problems with code formatting, seemingly
https://travis-ci.org/OmniSharp/omnisharp-emacs/builds/208066727#L1820

**Comment by alistair** [comment]
@sp3ctum It seems like there might be issues with the dotnetcore version of Omnisharp https://github.com/OmniSharp/omnisharp-roslyn/issues/666 so im wondering whether we actually want to be testing against ( and recommending ) the mono version be installed.

**Comment by razzmatazz** [comment]
@alistair I would like for the release after the next one have automatic server download mechanism that is the same as in vscode or atom, like detailed in https://github.com/OmniSharp/omnisharp-emacs/issues/275

This would make installation much more simple and user wouldn't need to care.

**Comment by sp3ctum** [comment]
Is the test failing or passing locally? Are you able to try it out?
If travis is acting differently, it's a bit of a problem.

In my work I've familiarized myself with Docker. If the travis continues to be a problem I could try to create a Docker container to run the tests in. This way the setup would be very simple, and the tests would be 100% reproducible (a big promise :smile: )

Any thoughts on this?

**Comment by alistair** [comment]
Been using docker at work as well for testing.   Its brilliant.

im getting the following
``` Ran 31 out of 32 specs, 0 failed, in 8.7 seconds.```

but im also still seeing

```   Code format
  can format the entire buffer contentsMark set

omnisharp--handle-server-response-packet error: 
(end-of-buffer).

Tried to handle this packet: 
((Type . "response") (Seq . 91) (Body (Changes) (Buffer . "public class CodeFormatTest { }
")) (Message) (Success . t) (Running . t) (Command . "codeformat") (Request_seq . 37))

This can mean an error in the handler function:
   (closure ((current-file . "/home/alistair/projects/omnisharp-emacs/test/MinimalProject/CodeFormatTest.cs") t) (input0) (let* ((new-buffer-contents (cdr (assoc (quote Buffer) input0)))) (omnisharp--set-bu
   ffer-contents-to current-file new-buffer-contents (line-number-at-pos) (omnisharp--current-column))))```

**Comment by razzmatazz** [comment]
@sp3ctum @alistair I see this repo has good updates:
 - https://hub.docker.com/r/jare/emacs/

test builds could get faster this way too..

I will create an issue

**Pull request closed without merging**
