### PR TITLE
Don`t add "mono" to server executable path if using omnisharp-roslyn shell script in UNIX.

### PR DESCRIPTION
**Pull request by retran**
In omnisharp-roslyn "scripts/Omnisharp" already runs mono, so we don`t need to add it to executable path.

### CODE REVIEW

**Comment by sp3ctum** [comment]
Good, thanks :)
How's omnisharp-roslyn working? I have yet to test it. I've kind of lost interest in development due to not being able to use this at work any longer.

**Comment by retran** [comment]
First of all, despite some lack of functionality(like "fix usings"), it works MUCH faster than omnisharp-server. And context actions for refactoring and fix code issues much smarter in omnisharp-roslyn.
Some actions in omnisharp-emacs doesn`t work, but i think it is not hard to fix as omnisharp-roslyn mostly exposes same api as omnisharp-server.

We are actively using omnisharp-emacs to develop our projects for Mono on MacOS and Linux, and very interested in further support for omnisharp-roslyn.

So, we doing some hacking around your code, plan to do it further, and will be glad if we can help in development of such a good tool.

**Comment by sp3ctum** [comment]
That sounds great! I'm so glad you find it useful.

**Comment by nosami** [comment]
Hey @retran I have some suggestions that will make emacs work much better with omnisharp-roslyn if you're interested!

Fix usings coming soon :)

**Comment by retran** [comment]
@nosami Of course, I'm interested :)

**Comment by nosami** [comment]
@retran @sp3ctum I quickly added some notes [here](https://github.com/OmniSharp/omnisharp-emacs/issues/178)

**Comment by sp3ctum** [comment]
Thanks Jason, seems like you summed it up quite nicely in that write up. I
think the new features sound awesome but I don't know if I have the energy
to write support for them at the moment. Not to sound disrespectful or
anything like that! I hope you understand.

I'll definitely keep it in mind and will continue maintaining the project.
I set up a day from my work to work on this but the date is uncertain.
We'll see. :)
11.6.2015 6.26 ip. "Jason Imison" <notifications@github.com> kirjoitti:

**Comment by nosami** [comment]
@sp3ctum No problem at all :) I realise that you don't have the motivation to work on this any more. I'd do it myself if I wasn't already so busy!

**Comment by retran** [comment]
@nosami I can try to implement support for TextChanges next weekend.

**Comment by nosami** [comment]
@retran that would be marvellous :)

**Pull request merged**
