### PR TITLE
[Roslyn] Actually use pipe for communication when starting omnisharp process.

### PR DESCRIPTION
**Pull request by razzmatazz**
`let` special form was binding `process-connection-type` locally and was
not setting global variable properly (I'm new to elisp, not so sure about the details – but it appears that `let` wasn't working here)

Also set `:noquery` so emacs would not ask for confirmation to kill OmniSharp
server processes on quit.

### CODE REVIEW

**Comment by razzmatazz** [comment]
oh, apparently I used `make-process` from emacs-25

**Comment by razzmatazz** [comment]
@sp3ctum – I think I have fixed this one too, now the fix should work with emacs-24 too

**Comment by razzmatazz** [comment]
@sp3ctum – not sure I understand your idea well..

The old code in `omnisharp-start-omnisharp-server` had `(let ((process-connection-type nil))` line that wrote over.. should I restore it somehow differently?

**Comment by razzmatazz** [comment]
@sp3ctum – isn't it that variables bound with`let` are local to the function they are defined in?

**Comment by sp3ctum** [comment]
I think it depends on the variable. But I forgot it was like that already 😁

**Comment by sp3ctum** [comment]
This is really great. I hope the bug never returns.

**Pull request merged**
