### PR TITLE
Update tests to use .NET CLI project

### PR DESCRIPTION
**Pull request by andschwa**
This is work-in-progress to update the integration tests and Travis to use .NET CLI.

The `MinimalSolution` was replaced with `MinimalProject`. The integration tests were updated to point to it. A few tests caused the entire suite to abort, and so were commented out in f9024e33a44c5364f71278f035e4f32390164e64 until I can get some help debugging them. Besides those disabled, just one (of the integration tests) fails.

The Travis setup was switched to install and use .NET CLI instead of Mono. I'm creating this PR early so I can test out the Travis build.

### CODE REVIEW

**Comment by andschwa** [comment]
Okay, at this point the failure is due to failed tests, not failing-to-run tests. This should help out with #219.

@sp3ctum any clue about the ones I had to disable, and the ones now failing?

**Comment by andschwa** [comment]
@sp3ctum I think `incremental-updates` and `feature-omnisharp-roslyn-support` diverged at a418e7b12803f068d56060e8eb8ef017b04242cd.

**Comment by sp3ctum** [comment]
I took a first glance at this, it's very nice! I'll try to make time to merge it in soon.
Do you have some work you'd still like to do before merging?

**Comment by andschwa** [comment]
@sp3ctum I think so yes; I wanted to rebase onto your branch instead of `incremental-updates`. I'll have to re-issue the PR.

**Pull request closed without merging**
