### PR TITLE
Update on README.md, in particular the installation and configuration sections

### PR DESCRIPTION
**Pull request by razzmatazz**
This my attempt to add more up-to-date documentation for the project. Also related to #266

### CODE REVIEW

**Comment by zestyr** [comment]
What about installation on Linux?

**Comment by razzmatazz** [comment]
@zestyr I'd love to add a link to www.omnisharp.net page where installation would be detailed for each platform and not on omnisharp-emacs.. can't find it though; will ask them..

I'd think it instructions would depend on what type of distro it is, .deb or .rpm

And since I'm using neither (macOS myself) I can't add them.

Would you be able submit that documentation? (As a PR or otherwise?)

**Comment by zestyr** [comment]
@razzmatazz ah, fair enough. 

I don't really have time to write some documentation right now, but under the omnisharp-roslyn [release page](https://github.com/OmniSharp/omnisharp-roslyn/releases), there are builds for Debian, Ubuntu, Fedora, CentOS, Red Hat, and OpenSUSE. 
For Arch Linux there's a handy [AUR package](https://aur.archlinux.org/packages/omnisharp-roslyn/). 

Other than that, there's some pretty easy build instructions [here](https://github.com/OmniSharp/omnisharp-roslyn#building).

**Comment by razzmatazz** [comment]
@zestyr – thanks – I will add these two things you mentioned to README, and maybe will test it on linux once I have my VMs ready

**Pull request merged**
