### PR TITLE
Start in folder mode if no solution is found.

### PR DESCRIPTION
**Pull request by dgalizzi**
Currently if no solution is found the server won't load. I propose to start the server in folder mode at the current file's directory instead of failing.

### CODE REVIEW

**Comment by sp3ctum** [comment]
Looks like the build was broken because an external dependency could not be installed. I removed it, so could you merge the master branch to this pull request so we can see if it can pass the tests? (it should, even without doing anything, I think)

**Comment by dgalizzi** [comment]
I merged but still fails (different error though). I also answered your comments on the code, apparently they got lost from here because I rebased.

**Comment by sp3ctum** [comment]
Can you merge master to this branch to see if the build will succeed?

**Comment by dgalizzi** [comment]
It's up to date with the master branch and I added the message. If there's anything else, please don't hesitate to tell me.

**Comment by sp3ctum** [comment]
Looks like restarting the build fixed it, thanks!

**Pull request merged**
