### PR TITLE
Update tests to use .NET CLI

### PR DESCRIPTION
**Pull request by andschwa**
This is a redo #221, rebased onto `feature-omnisharp-roslyn-support`. 

Four tests caused the entire suite to abort, and so were disabled in 5ea4a78b5b9f5cfbc708cd4670976f32c32cdd69 until we can fix them.

The `MinimalSolution` was replaced with `MinimalProject`. The integration tests were updated to point to it, and use the term `project` over `solution`. While ab13cf34f4ba26206342674e84a9c4c72477e4e4 introduced a `dotnet new` project, unfortunately, .NET CLI very quickly becomes out of date (the `dnxcore50` framework was deprecated a while ago). It's now updated to use the `netcoreapp1.0` framework (which is the current supported framework by .NET CLI 1.0.0-rc2; note that `netstandardapp1.5` will be the new one, and was briefly supported, but is not currently) with the `Microsoft.NETCore.App` package (used to obtain the "shared" (but not, since we're not `"type": "platform"`) host).

The Travis setup was switched to install and use .NET CLI instead of Mono on Ubuntu 14.04; .NET CLI deprecates Mono entirely. The default Travis environment uses Ubuntu 12.04, which is not supported by .NET Core.

### CODE REVIEW

**Comment by andschwa** [comment]
For what it's worth, the performance of `incremental-updates` is *much* better 😄.

**Comment by andschwa** [comment]
Also, this installs and runs `dotnet restore` instead of committing the `project.lock.json`. I could go either way on this, but calling `dotnet restore` ensures our CI tests that `omnisharp-emacs` with any changes made to the lockfiles. On the other hand, the `dotnet` package and `OmniSharp` binaries are pinned... so I really have no strong feelings either way.

**Comment by andschwa** [comment]
Bah let me clean up the disabled tests.

**Comment by sp3ctum** [comment]
This looks very nice. Nice work!
Let me know when you are done and I will merge this in.

So refreshing to see the build pass (even though some things are disabled). I had forgotten about [this gem](https://travis-ci.org/OmniSharp/omnisharp-emacs/builds/127425881#L1782) :smile:

**Comment by andschwa** [comment]
@sp3ctum Nice timing! I'm done (as long as that build passes). I figured out how to mark tests as pending instead of commenting them out 😆.

**Comment by sp3ctum** [comment]
It passed :+1: 
Should I merge?

**Comment by andschwa** [comment]
Do it!

**Pull request merged**
