### PR TITLE
[WIP] Add some status check related functions

### PR DESCRIPTION
**Pull request by supermomonga**
# Changes

Added following functions.

- `omnisharp-server-running-p`
- `omnisharp-file-in-current-project-p`
- `omnisharp-buffer-file-in-current-project-p`

# Purpose

Allow user to write hooks or functions which depends on server status.

## Example

Execute formatting automatically only if the server process is running and buffer file is part of project which handled by current server process.

```lisp
(defun my-omnisharp-after-save-hook ()
  (when (and (omnisharp-server-running-p) (omnisharp-buffer-file-in-current-project-p))
    (omnisharp-code-format-entire-file)))

(defun my-omnisharp-hook ()
  (add-hook 'before-save-hook 'my-omnisharp-after-save-hook nil t))

(add-hook 'omnisharp-mode-hook 'my-omnisharp-hook)
```

### CODE REVIEW

**Comment by razzmatazz** [comment]
a couple of comments:
 - i don't like having `omnisharp-server-running-p` exposed because
   a) there are plans to support multiple projects which would require multiple servers to be started;
   b) we might later have a delayed-server initialization added functionality that would delay-start the server once there is a request

    not sure what is the alternative for `omnisharp-server-running-p`.. can we just have those `omnisharp-buffer-file-in-current-project-p` predicates check if the server is available themselves?

 - same thing with `-current-project-p` there could be multiple projects loaded so that there is no one that is 'current'. i think the functionality is ok with these predicates it is just the naming could be better..

**Comment by supermomonga** [comment]
@razzmatazz Sorry for delay 🙇 

Supporting multiple server processes is fantastic! I agree that we should add/change exposed functions/variables carefully to minimize breaking changes in future.

> can we just have those omnisharp-buffer-file-in-current-project-p predicates check if the server is available internally themselves?

I like this.

> same thing with -current-project-p there could be multiple projects loaded so that there is no one that is 'current'. i think the functionality is ok with these predicates it is just the naming could be better..

How about `omnisharp-get-server-info-by-path`? It takes file/directory path and returns assoc list which has a same structure as `make-omnisharp--server-info`'s.

Usecase:

```lisp
(defun my-omnisharp-after-save-hook ()
  (let* ((server-info (omnisharp-get-server-info-by-path
                       (buffer-file-name (current-buffer))))
         (started-p (assoc 'started? server-info)))
    (when started-p
      (omnisharp-code-format-entire-file))))


(defun my-omnisharp-hook ()
  (add-hook 'before-save-hook 'my-omnisharp-after-save-hook nil t))

(add-hook 'omnisharp-mode-hook 'my-omnisharp-hook)
```

**Comment by razzmatazz** [comment]
@supermomonga I would rather prefer not to expose inner structure of the server information to the user.. 

can we have something like `omnisharp-buffer-file-managed-p` ? which would test if both of the following is true:
 - the server is up
 - the server (any of the servers, actually, in the future) knows of the file and is "managing" it -- so it can format it and do anything else

it would take a parameter which could be either a:
 - `buffer`, or a
 - filename

**Comment by supermomonga** [comment]
Yeah, that sounds better. 

>(still not sure about the naming)

If it can take both buffer or filepath, should it be `omnisharp-buffer-or-file-managed-p`?

And, If we want to take care of buffer parameter, Can we add two functions `omnisharp-buffer-managed-p` and `omnisharp-file-managed-p`? I prefer it than a function which can takes some types of parameter.

---

btw, in this project, is it better `?` prefixed naming than `-p` prefixed?

**Comment by razzmatazz** [comment]
Splitting into to fns is probably better, as you said.

As for `?` or `-p` suffix, elisp code convention says it should be `-p` for multi-word predicate name and `p` for a single word, from:
 - https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html

https://www.gnu.org/software/emacs/manual/html_node/elisp/Type-Predicates.html has examples

**Comment by supermomonga** [comment]
Thanks! I'll add `omnisharp-buffer-managed-p` and `omnisharp-file-managed-p`.

**Pull request closed without merging**
