### PR TITLE
[Roslyn] Make it possible again to specify VS solution files again

### PR DESCRIPTION
**Pull request by razzmatazz**
omnisharp-roslyn supports loading Visual Studio .sln files again

This is an attempt to fix https://github.com/OmniSharp/omnisharp-emacs/issues/227

### CODE REVIEW

**Comment by sp3ctum** [comment]
This looks good to me. Great work, and great research in https://github.com/OmniSharp/omnisharp-emacs/issues/227 :+1: 

I would like to see the build pass before merging this, though.
Could you help with fixing the travis build? I get a weird error there:
https://travis-ci.org/OmniSharp/omnisharp-emacs/builds/149667608

**Comment by razzmatazz** [comment]
@sp3ctum sure, will take a look!

**Comment by razzmatazz** [comment]
@sp3ctum – yay, I seem to have been successful in tricking the build to work!

**Comment by sp3ctum** [comment]
Awesome work, thank you very much!

**Pull request merged**
